title:            Haddon Community Learning Centre
description:
logo:             site-logo.png
disqus_shortname:
search:           false
gsearch:          true
rss:              true
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
baseurl: ''
url:              http://haddonlearning.org.au
date: 2014-08-22

# Owner/author information
owner:
  name:           Haddon Community Learning Centre
  avatar:         site-logo.png
  email:          manager@haddonlearning.org.au
  # Social networking links used in footer. Update and remove as you like.
  facebook: //facebook.com/HaddonCommunityLearningCentre

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: DB178A2E2729150AD2FB760AB8017F12

#Assets link
assets: //shakna-israel.github.io/haddonRevamp/assets

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Us
    url: /about/
  - title: Enrolments
    url: /enrolment/
  - title: Courses & Activities
    url: /courses/
  - title: Room Hire
    url: /hire/
  - title: Advertising
    url: /advertising/
  - title: Contact Us
    url: /contact/
# An example external link:
# - title: External Link
#   url: http://awesomewebsite.com
#   external: true

acfe: docx/VET Student Enrolment Form Version 2014.docx

#Contact Details
phone_link: 0061353427050
phone: (03) 5342 7050

future:      true
highlighter: false
markdown:    kramdown

gems:
  - jekyll-sitemap

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Sitemap Settings
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  ignore: ["lib", "config.rb", "Gemfile", "Capfile", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "vendor", "/_posts/examples", "README.md", ".gitignore", ".gitattributes", "404.md", "CNAME", "LICENSE", "favicon.ico", "favicon.png", "feed.xml", "links.jsonp", "package.json", "post.thor", "publication_details.md", "search.html", "tags.html", "_plugins", "_layouts", "_includes"]
  rooturl: ''
  siteurl: 'https://haddonlearning.org.au/'
  relativeLinks: 'https://haddonlearning.org.au/links.jsonp'
  media: 'assets/img'
  metadata:
    _posts:
      - name: "comments"
        field:
          label: "Comments"
          element: "checkbox"
          value: "true"
      - name: "share"
        field:
          label: "Share Link"
          element: "checkbox"
          value: "true"
      - name: "acfe"
        field:
          label: "ACFE Course"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "category"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "articles"
              value: articles
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Page Link"
          placeholder: "Link to page, e.g. /about/"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Page Title"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "published"
        field:
          element: "hidden"
          label: "Published"
          value: "true"
      - name: "slider"
        field:
          label: "Image Gallery"
          element: "checkbox"
          value: "true"
      - name: "slide1_image"
        field:
          label: "First Image Gallery Image"
          placeholder: "DSCF0069.jpg"
          element: "text"
      - name: "slide2_image"
        field:
          label: "First Image Gallery Image"
          placeholder: "DSCF0069.jpg"
          element: "text"
      - name: "slide3_image"
        field:
          label: "First Image Gallery Image"
          placeholder: "DSCF0069.jpg"
          element: "text"

include: [".htaccess","_pages"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "vendor", "/_posts/examples"]
